### ISSUE TITLE
App sends data to Parse

### ISSUE THREAD

**Issue by sampeckham** [paddybc/TearfundDisasterResponse#1]
Merge and test in the main branch

**Comment by UsAndRufus** [comment]
Patrick and I did this on Monday night, could do with a bit more testing possibly, but it all seems to work.

**Comment by sampeckham** [comment]
Just looking in Parse can't see any data in there - maybe not looking in the right place?

**Comment by UsAndRufus** [comment]
Pinned a message in the Slack channel explaining how to view

**Comment by UsAndRufus** [comment]
Works.
