### ISSUE TITLE
Free text field

### ISSUE THREAD

**Issue by sampeckham** [paddybc/TearfundDisasterResponse#10]
Should we add a free text field for additional notes at the end of the Question tree?

**Comment by UsAndRufus** [comment]
I was thinking about this the other day. On one hand, it lets the user add data they wouldn't be able to before. On the other, if the questions are good enough they probably wouldn't need to and it clutters up the app a bit.

**Comment by sampeckham** [comment]
Yeah. I think it really depends on what Tearfund need to know. If it's just raw facts to get a snapshot and make decisions on when/where to go and help, it's probably not needed. If they need context to help in the process then it's really useful. On the flip side, users can be frustrated if they want/need to report something the app doesn't ask them about - you can never think of everything ahead of time!

**Comment by HappySmilyGuy** [comment]
From Joel: "...a space for comments would be good. I think that was in the initial brief. As long as it’s super simple!"
